### ISSUE TITLE
Native installs do not work from repo Arm64 Ubuntu

### ISSUE THREAD

**Issue by thelamer** [fedarovich/qbittorrent-cli#10]
i386 needs to be swapped to arm64 here
https://dl.bintray.com/fedarovich/qbittorrent-cli-debian/dists/bionic/Release

Need a packages file dedicated for arm64 here: (currently they are merged in the armhf pacakges file)
https://dl.bintray.com/fedarovich/qbittorrent-cli-debian/dists/bionic/main/binary-arm64/

If you do not have arm64 hardware to test this on you can always use Docker first run: 
```
docker run --rm --privileged multiarch/qemu-user-static:register --reset
```

Then this dockerfile should do the trick

```
FROM lsiobase/ubuntu:arm64v8-bionic
# add repo and install qbitorrent-cli
RUN \
 apt-get update && \
 apt-get install -y \
        gnupg && \
 curl -s https://bintray.com/user/downloadSubjectPublicKey?username=fedarovich | apt-key add - && \
 echo "deb https://dl.bintray.com/fedarovich/qbittorrent-cli-debian bionic main" > /etc/apt/sources.list.d/qbitorrent.list && \
 apt-get update && \
 apt-get install -y \
        qbittorrent-cli
```

**Comment by fedarovich** [comment]
It looks like I had an error in my build scripts. It should be fixed now, but I could not verify it myself right now, as I don't have ARM64 Ubuntu at the moment. I'll try to install it on my Raspberry PI 3 in the nearest future.

**Comment by thelamer** [comment]
All good thanks !
