### ISSUE TITLE
/usr/bin/qbt  --- file or directory not found inside docker container

### ISSUE THREAD

**Issue by mrfatboy** [fedarovich/qbittorrent-cli#109]
I am trying to run 'qbt' in a bash script from inside a qbittorrent docker container on Ubuntu 22.04. I am using the the full path /usr/bin/qbt.  I'm getting qbt file or directory not found.

I have built several systems just like that a couple of months ago and it has always worked perfectly.

qbt is installed and is in the /usr/bin folder outside docker in the normal system.  For some reason, qbt is not in the /usr/bin folder inside the container.  I have always installed it the same way.

Has something changed? Am missing something? Insights?

Thanks

**Comment by mrfatboy** [comment]
I finally tracked down the issue.  It seems that the latest docker container of qbittorrent has a bug in it.  It must have just been introduced recently. I tracked the container version I used several months ago and low and behold 'qbt' was found in /usr/bin.

For anybody having the same problem use docker qbittorrent version 4.6.3.  At the time of this writing 4.6.5 has the problem.

**Comment by mrfatboy** [comment]
I have been digging around more trying to understand why qbittorrent-cli was not in the latest docker qbittorrent container.

From the [website](https://hub.docker.com/r/linuxserver/qbittorrent) it states it was pulled because of the below reason.

25.05.24: - Remove qbittorrent-cli as it still requires openssl 1.1 which is EOL.

I don't know much if anything about these things but will qbittorrent-clli be upgraded so it will be included back into the docker qbitorrent docker containers?

**Comment by fedarovich** [comment]
qbittorrent-cli has been supporting the modern `openssl 3` from May 1st, 2022, so I'm really surprised to see that they state it does not. I guess, they were still trying to use the old version compiled with `netcore3.1`, instead of the modern one compiled with `net6.0`. So, unfortunately, this question should be forwarded to the maintainers of this docker image.

Anyway, you can create your own docker image based on theirs, and include qbittorrent-cli from the releases page in it: 
[v1.8.24148.1 (x64)](https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.8.24148.1/qbt-linux-x64-net6-1.8.24148.1.tar.gz)
[v1.8.24148.1 (arm64)](https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.8.24148.1/qbt-linux-arm64-net6-1.8.24148.1.tar.gz)

**Comment by Roxedus** [comment]
The container needs https://github.com/fedarovich/qbittorrent-cli/issues/103 addressed

**Comment by aptalca** [comment]
> Anyway, you can create your own docker image based on theirs, and include qbittorrent-cli from the releases page in it:

It seems the binaries linked in the above post, the ones compiled with (and listed as) `net6` are the glibc ones.

We are referring to the alpine binaries as not being openssl3 compatible:
- https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.8.24148.1/qbt-linux-alpine-x64-1.8.24148.1.tar.gz
- https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.8.24148.1/qbt-linux-alpine-arm64-1.8.24148.1.tar.gz

Please correct me if my assumption is wrong.

**Comment by fedarovich** [comment]
@aptalca You are right, Alpine binaries are outdated. I'll create a new release with the updated binaries.

**Comment by fedarovich** [comment]
@aptalca here are the updated binaries for Alpine:

- x64: https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.8.24199.1/qbt-linux-alpine-x64-net6-1.8.24199.1.tar.gz
- armhf: https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.8.24199.1/qbt-linux-alpine-arm-net6-1.8.24199.1.tar.gz
- arm64: https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.8.24199.1/qbt-linux-alpine-arm64-net6-1.8.24199.1.tar.gz

**Comment by aptalca** [comment]
@fedarovich I forgot to say thanks. The cli binaries were added back into the linuxserver docker image back in July (https://github.com/linuxserver/docker-qbittorrent/pull/317). This issue can be closed now.
