### ISSUE TITLE
404 error when pausing or resuming torrents

### ISSUE THREAD

**Issue by poetimp** [fedarovich/qbittorrent-cli#117]
Pause/Resume changed to Stop/Start in qbittorrent 5.0 . Any attempt to pause or restart results in a 404

**Comment by fedarovich** [comment]
Yes, it's a known issue and the fix is on the way. I expect the new release to be available tomorrow.

**Comment by fedarovich** [comment]
Fixed in [v1.8.24285.1](https://github.com/fedarovich/qbittorrent-cli/releases/tag/v1.8.24285.1)
