### ISSUE TITLE
Add binaries for Debian 10 "Buster"?

### ISSUE THREAD

**Issue by AlexaraWu** [fedarovich/qbittorrent-cli#12]
The current stable distribution of Debian is version 10 "Buster", released on 6 July 2019.

**Comment by fedarovich** [comment]
Yes, I will add the packages both Debian 10 and Ubuntu 19.04 in the nearest future.

**Comment by fedarovich** [comment]
Added packages for Debian 10 and Ubuntu 19.04. Updated documentation.
