### ISSUE TITLE
Request - extended properties

### ISSUE THREAD

**Issue by Jorman** [fedarovich/qbittorrent-cli#14]
Hi is possible to have some extra command to be used with properties?

I mean properties return all properties of one torrent, but if I want only some data I've to grep and sed all output.
So is possible to have some like
qbt torrent properties-size HASH --url http://localhost:8081 -> to have the size
or
qbt torrent properties-seedingtime HASH --url http://localhost:8081 -> to have the seeding time

and so on?

Let me know if you think can be usefull

Jo

**Comment by fedarovich** [comment]
Hi,
At the moment it is not possible, but I think it is a good feature to add.
I'll try to implement it for the next release.

**Comment by Jorman** [comment]
Hi @fedarovich 
Thanks for your support

**Comment by fedarovich** [comment]
I've added the format option and at is available in the latest nightly build. You can use `property` format to get a value of a single property. More information is available in [wiki](https://github.com/fedarovich/qbittorrent-cli/wiki/Output-Formats).

For example, to get a torrent size, you can use the following command:
```
qbt torrent properties HASH -F property:name=Size
```

I will likely make the release 1.5 at the end of this week.

**Comment by Jorman** [comment]
Thank you very much
