### ISSUE TITLE
Delete torrent after completion

### ISSUE THREAD

**Issue by Brodieman** [fedarovich/qbittorrent-cli#18]
I am working on a PowerShell script that will help automate my life.  In qbittorrent I am calling a PS1 file and passing arguments like torrent name, path, and hash (in the run external program after completion section).  It's working to get that info however when I do qbt torrent delete $Hash to try and delete the torrent that finished it will not.  It will manually if I type that in or manually run the script but not launching from the PS1 from qbittorrent.

Is there a limitation from launching the PS1 from qbittorrent?  The script DOES run after the torrent is done, I have tested with popups.  I can see the proper variables getting the information from qbittorrent.  It's just won't process that command

Thanks

PS.  I know this is not a qbittorrent page but I am thinking that the person who wrote this CLI might be familiar with working in qbittorrent enough to maybe know :D

**Comment by Brodieman** [comment]
Through testing I noticed that the qbt command weas not recognized by just typing qbt, need to be the full path.

**Comment by alivefromupstairs** [comment]
>Through testing I noticed that the qbt command weas not recognized by just typing qbt, need to be the full path.

Have you tried adding `qbt` to your PATH?
