### ISSUE TITLE
Issue with connecting when SSL is enabled

### ISSUE THREAD

**Issue by blackthorn87** [fedarovich/qbittorrent-cli#19]
I have SSL enabled, but get the following error:

The SSL connection could not be established, see inner exception.
The remote certificate is invalid according to the validation procedure.

Is there a way for me force accept the SSL Cert in some config somewhere?

Thanks.

**Comment by fedarovich** [comment]
In order to disable certificate validation you can run the following command:
```
qbt network settings -i true
```

**Comment by blackthorn87** [comment]
Thank you. This worked perfectly.
