### ISSUE TITLE
Regression: Error when accessing remote qbt: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by adamryczkowski** [fedarovich/qbittorrent-cli#2]
After migration to qbittorrent-cli 0.11.18178-1 I get error `Object reference not set to an instance of an object.` on any attempt to contact the remote server, e.g. with

`qbt torrent list --url http://10.55.181.104:8080 --password 'secret_pa$$word' --username adam`

Server uses qbittorrent v4.1.1.

Walkaround:
downgrade to version `0.10.18151-1`.

**Comment by fedarovich** [comment]
Thank you for reporting the issue.
I can confirm this bug.

**Comment by fedarovich** [comment]
I think I have fixed the issue.
Could you please check the latest version 0.11.18192-1?

**Comment by fedarovich** [comment]
Fixed in 0.11.18192.1
