### ISSUE TITLE
Label Support

### ISSUE THREAD

**Issue by BzowK** [fedarovich/qbittorrent-cli#20]
Hey Guys - 

Great tool - Currently using it along with other scripts to automate some of my downloads.  It works very well, yet cannot figure out how (or feature is missing) to assign a label to a torrent/magnet when adding it using the CLI.  The reason I require this is because the label assign designates the final save path for the download.

Is this currently possible or if not being considered?  Thank You!

**Comment by fedarovich** [comment]
Hello,

At the moment qBittorrent supports two concepts for associating additional data to the torrents: categories and tags.

Only one category can be set for the torrent. The category can be used for automatic torrent management mode (ATTM). If ATTM is enabled for the torrent, the torrent will be saved to the folder defined in the category settings. Categories are fully supported by qBittorrent CLI. For example, to add a torrent with a specific category and ATTM enabled you can use the following command:
```
qbt torrent add file <path> -c <category> -a true
```
The category must already exist at the time you issue this command. You can use [`qbt category`](https://github.com/fedarovich/qbittorrent-cli/wiki/qbt-category) subcommands to add/edit/delete categories.

Tags are a bit newer concept. There can be more than one tag per torrent. Alas, tag management is not available in qBittorrent WebAPI at the moment, so it is not available in qBittorrent CLI either. It will likely be available in qBittorrent 4.2 (currently in beta) and qBittorrent CLI 1.6.

**Comment by runaroundhome** [comment]
Any plans to add tags, now that's it's officially released in qbt?

**Comment by fedarovich** [comment]
Yes, sure. Last week I released the new version of the underlying library with the support of all features of the latest qbittorent version. Now I can add tag support as well as some other features to this tool. I will hopefully release a new version till the end of this week.

**Comment by fedarovich** [comment]
Implemented in v1.6.20334.1.
