### ISSUE TITLE
Pause torrent with specified category

### ISSUE THREAD

**Issue by rErEaT** [fedarovich/qbittorrent-cli#24]
Like qbt torrent pause ALL -c CategoryName

does it possible?

**Comment by fedarovich** [comment]
Well, it is possible, though not directly, but with some shell magic.

Basically, you should do the following steps:

1. Get the list of torrents filtered by category in some parceable format, e.g. JSON.
2. Extract the torrent hashes from it.
3. Pass the hashes to `qbt torrent pause` one by one.

For `powershell` you can use something like that:
```
 (qbt torrent list -c MyCategory -F json | ConvertFrom-Json).hash | foreach { qbt torrent resume $_ }
```

In `bash` it is easier to use CSV format as you can use `awk` to extract the hash. You can use the following script:
```
qbt torrent list -c MyCategory -F csv | awk -F "," 'NR > 1 {print $1}' | xargs -n 1 ./qbt torrent pause
```

I will probably add some additional output formats in the next `qbt` versions to make similar scenarios easier.

**Comment by rErEaT** [comment]
Oh thanks.

Can u help me how can i make a script what pause the torrent and unrar after downloaded + delete the rar files after unrar complete :|

Like this one:
cmd /c timeout /t 15 & "E:\Programok\WinRAR\RAR.exe" x -r "%F\*.rar" "%F" && del /f "%F\*.r'[0-9]{2}'" && del /f "%F\*.sfv*"

but i dont know how to open powershell in the background to pause first :/

**Comment by fedarovich** [comment]
In order to run a command in powershell you can use the following:
```
powershell -Command "<command>"
```

So, if I correctly understand what you'd like to achieve, you can use something like that:
```
powershell -Command "(qbt torrent list -c MyCategory -F json | ConvertFrom-Json).hash | foreach { qbt torrent resume $_ }" && cmd /c timeout /t 15 & "E:\Programok\WinRAR\RAR.exe" x -r "%F*.rar" "%F" && del /f "%F*.r'[0-9]{2}'" && del /f "%F*.sfv*"
```

**Comment by rErEaT** [comment]
powershell -Command "(qbt torrent list -c iPT -F json | ConvertFrom-Json).hash | foreach { qbt torrent resume $_ }"

This command will stop/pause my torrent what added in iPT category after downloaded? :)
![picture](https://user-images.githubusercontent.com/2604798/71090860-3c67a500-21a4-11ea-9777-9883a3078dde.png)

**Comment by rErEaT** [comment]
powershell -Command "(qbt torrent list --url http://localhost:8080 -c MyCategory -F json | ConvertFrom-Json).hash | foreach { qbt torrent pause %I --url http://localhost:8080 }" && cmd /c timeout /t 15 & "E:\Programok\WinRAR\RAR.exe" x -r "%F\*.rar" "%F" && del /f "%F\*.r*" && del /f "%F\*.sfv*"

it doesn't work.

Only works if i just use this:
powershell -Command "(qbt torrent list --url http://localhost:8080 -c MyCategory -F json | ConvertFrom-Json).hash | foreach { qbt torrent pause %I --url http://localhost:8080 }"

why doesn't run cmd ?

**Comment by rErEaT** [comment]
Works with a batch file what i run from qBitorrent :)

> \RUN.bat "%I" "%F"

`powershell -Command "(qbt torrent list --url http://localhost:8080 -c MyCategory -F json | ConvertFrom-Json).hash | foreach { qbt torrent pause %1 --url http://localhost:8080 }" && cmd /c timeout /t 15 & "E:\Programok\WinRAR\RAR.exe" x -r "%2\*.rar" "%2" && del /f "%2\*.r*" && del /f "%2\*.sfv*"`

**Comment by rErEaT** [comment]
Oh it wont respect the category, after a torrent downloaded it will paused anyway :-/

**Comment by rErEaT** [comment]
After it unrar the torrent, how can i delete only the rar,r01....r99 files? :)

powershell Get-ChildItem $Path | Where{$_.Name -Match "*.r[0-9]{2}"} | Remove-Item
it doesnt work :(

**Comment by rErEaT** [comment]
"qbt torrent list --url http://localhost:8080 -c MyCategory -F json | ConvertFrom-Json).hash"

have to match with the "%I" placeholder what the script gets from qBitorrent right?
