### ISSUE TITLE
Repo error

### ISSUE THREAD

**Issue by thelamer** [fedarovich/qbittorrent-cli#25]
Today started getting back 
```
E: Failed to fetch https://dl.bintray.com/fedarovich/qbittorrent-cli-debian/dists/bionic/main/binary-amd64/Packages.gz  File has unexpected size (1103 != 1270). Mirror sync in progress? [IP: 34.214.69.171 443]

   Hashes of expected file:

    - Filesize:1270 [weak]

    - SHA256:8a7a3f1c110618151ef5611cea972bec95f17d72b0888ca569cc7814699d122b

    - SHA1:91e02eb198a48d3b9f0a7970f5f8f59b77c5703d [weak]

    - MD5Sum:23fd0c84047b6960e84731f1f4dcff0f [weak]

   Release file created at: Tue, 17 Dec 2019 06:45:46 +0000
```

Let me know if you need anymore information .

**Comment by basecaseFM** [comment]
I'm confused. What can be achieved with this project that cant be done with
the webui?

**Comment by fedarovich** [comment]
I guess, there was some issue with bintray servers. It seems to work now.

**Comment by thelamer** [comment]
No still busted on my side https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-qbittorrent/detail/master/168/pipeline

**Comment by fedarovich** [comment]
Hm, I can't understand what's hapenning. Yes, it fails when I try to build your Dockerfile. But installs normally if I install it on a usual Ubuntu Bionic system.

**Comment by thelamer** [comment]
Let me debug on my side I did no further testing outside of the docker build.

**Comment by thelamer** [comment]
The information is accurate: 
```
curl -sL https://dl.bintray.com/fedarovich/qbittorrent-cli-debian/dists/bionic/main/binary-amd64/Packages.gz | md5sum
81a63559cb09c6c921477315a433e720  -
curl -sLI https://dl.bintray.com/fedarovich/qbittorrent-cli-debian/dists/bionic/main/binary-amd64/Packages.gz |grep Content-Length
Content-Length: 1103
```

```
curl -sL https://dl.bintray.com/fedarovich/qbittorrent-cli-debian/dists/bionic/Release | grep main/binary-amd64/Packages.gz
 23fd0c84047b6960e84731f1f4dcff0f             1270 main/binary-amd64/Packages.gz
```

That Release file needs to be regenerated against the current files in the repo.

**Comment by thelamer** [comment]
Looks like for bintray you can trigger a metadata calculation using their api: 
```
curl -X POST -umyuser:<API_KEY> https://api.bintray.com/calc_metadata/myorg/myrepo/
```

Reference: 
https://www.jfrog.com/confluence/display/BT/Bintray+REST+API#BintrayRESTAPI-ScheduleMetadataCalculation

**Comment by fedarovich** [comment]
Thank you for your help! It seems to work now.

**Comment by thelamer** [comment]
No, thank you for taking the time to troubleshoot this.
You might want to shift to the non V1 endpoint here: 
https://github.com/fedarovich/qbittorrent-cli/blob/master/setup/linux/publish-packages.sh#L34
Though this just might be a one off sync problem.

**Comment by fedarovich** [comment]
Yes, I guess I should update this script.
