### ISSUE TITLE
Clear all trackers command for specified torrent with hash

### ISSUE THREAD

**Issue by rErEaT** [fedarovich/qbittorrent-cli#26]
qbt torrent tracker clear [arguments] [options]

is it possible? :)

after i run it i wanna add my own trackers what i want with "qbt torrent tracker add [arguments] [options]" command

**Comment by fedarovich** [comment]
There is no such command in the current version, though I guess I can add this command in version 1.6. I've added it as the issue #27

At the moment you can use the similar approach, as in issue #24:

1. Get the tracker list as JSON
2. Extract tracker URLs from it
3. Pass them to `qbt torrent tracker delete` one by one.

**Comment by rErEaT** [comment]
thanks :)
but sure the command would be nice!
I close this :)
