### ISSUE TITLE
Search for hash, name etc in list or json

### ISSUE THREAD

**Issue by rErEaT** [fedarovich/qbittorrent-cli#29]
It would be nice if we can search for Name of torrent then it leaves that torrent's hash for example.

qbt torrent list -f paused -F json | Where Name = "Something" then send me that hash what torrent named with "Something"

**Comment by fedarovich** [comment]
Hello,

in powershell you can use something like that:
```
((qbt torrent list -F json | ConvertFrom-Json) | where { $_.name -eq "Something" }).hash
```

**Comment by rErEaT** [comment]
Oh well, so we can close it :D 
thanks for this help!!
