### ISSUE TITLE
Specifying download location doesn't work for "qbt torrent add url"

### ISSUE THREAD

**Issue by conectionist** [fedarovich/qbittorrent-cli#34]
**Description**
I tried adding a new torrent via URL, while specifying the download location, but I get an error saying that the command is not found.
This what my command looks like:

`qbt torrent add url https://some_site.com/mytorrentfile --folder /home/user/Downloads`

I also tried the -f option but it still doesn't work.

**Expected result**
Torrent is added successfully and is being downloaded to the specified folder.

**Actual result**
I receive the following error:
`[2] 10951`
`--folder: command not found`

The "[2] 10951" part makes me think that some kind of background job was created, but when I list the torrents via qbt torrent list, I don't see my new torrent.

**Additional info**
OS: Linux Mint 19.1 
qbt version: 1.5.19350.1

Please let me know if I'm using the command incorrectly or if there's some workaround I can use.

Thank you!

**Comment by fedarovich** [comment]
I was not able to reproduce the issue.

I can suggest that the URL could contain some characters that are interpreted by your shell (is it bash?) in some special way. Could you try enclosing your URL in quotes, please? I guess it may help.

Could you also say what version of qBittorrent you use, please?

**Comment by conectionist** [comment]
Enclosing the URL in quotes did the trick.
Thank you very much for your help!
