### ISSUE TITLE
Opensuse Tumbleweed repo fails

### ISSUE THREAD

**Issue by mgaulton** [fedarovich/qbittorrent-cli#38]
Added the repo as noted in the wiki and its failing on the most recent tumbleweed.

server6:~ # zypper se qbittorrent-cli
Loading repository data...
Reading installed packages...

S | Name            | Summary                                 | Type
--+-----------------+-----------------------------------------+--------
  | qbittorrent-cli | qBittorrent remote command line client. | package
server6:~ # zypper in qbittorrent-cli
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libssl47 needed by qbittorrent-cli-1.4.19211-2.x86_64
 Solution 1: do not install qbittorrent-cli-1.4.19211-2.x86_64
 Solution 2: break qbittorrent-cli-1.4.19211-2.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): c
server6:~ # zypper se libssl
Loading repository data...
Reading installed packages...

S | Name                     | Summary                                | Type
--+--------------------------+----------------------------------------+--------
  | libssl48                 | An SSL/TLS protocol implementation     | package
  | libssl48-32bit           | An SSL/TLS protocol implementation     | package
  | libssl48-32bit-debuginfo | Debug information for package libssl48 | package
  | libssl48-debuginfo       | Debug information for package libssl48 | package
server6:~ #

**Comment by fedarovich** [comment]
Yes, I guess I must update the packages. But we are having huge issues with the Internet in our country for several days already. I'll do it when the Internet starts to work normally.
For now you can try to use a [qbt-linux-x64-1.5.19350.1.tar.gz](https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.5.19350.1/qbt-linux-x64-1.5.19350.1.tar.gz) I guess it should work with libssl48 too.

**Comment by mgaulton** [comment]
Thanks, no huge rush. Just wanted to bring it to your attention.
I ended up using that bundle and its working fine.

**Comment by fedarovich** [comment]
Fixed
