### ISSUE TITLE
crontab can't run qbt, why?

### ISSUE THREAD

**Issue by PHCSJC** [fedarovich/qbittorrent-cli#39]
this is success in shell, I have config user password url by "qbt settings set":
qbt torrent list

this is also success in crontab:
03 13 * * * qbt torrent --help >>/tmp/ccc 2>>/tmp/ccc

but, this is failed in crontab, never running, /tmp/ccc is empty
03 13 * * *  qbt torrent list >>/tmp/ccc 2>>/tmp/ccc

thanks!

my system is debian 10 x64.
qbt --help
1.5.19350.1

QBittorrent version:    4.1.5                                                                                                                                    API version:            2.2.0                                                                                                                                    Legacy API version:     23                                                                                                                                       Legacy API min version: 23

**Comment by fedarovich** [comment]
I need to investigate why it outputs nothing.

Are you running qbittorent and qbt on the same machine and on the default port? If not, you may need to explicitly specify `--url` parameter in the command if running from crontab.

**Comment by fedarovich** [comment]
As there is no screen available when the command is run by cron, it will fail with the default output format as it tries to get the screen witdh. JSON or CSV output format must be used for non-interactive scenarios, e.g.
```
qbt torrent list -F json
```
