### ISSUE TITLE
Download in sequential order ?

### ISSUE THREAD

**Issue by Entretoize** [fedarovich/qbittorrent-cli#40]
I added qbittorrent and qbittorrent-nox on my debian server to have a good upload ratio. I'm using it to download films and watch them while it downloads, but currently I have to manually set "Download in sequential order" using the web interface to be able to stream the film without interuption.
Is it possible to ask qbttorrent to download in sequential order when adding a torrent ?

**Comment by fedarovich** [comment]
Yes, you can use `--sequential` (or just `-s`) option.

**Comment by Entretoize** [comment]
Thank you I'll test it.
