### ISSUE TITLE
add torrent with skip hashcheck?

### ISSUE THREAD

**Issue by foxi69** [fedarovich/qbittorrent-cli#41]
Is there any way to do it? :D

and/or with Superseed? :)

**Comment by fedarovich** [comment]
Yes, you can add torrent with skipping hashcheck. You can use `--no-check`  (or just `-n`) option for that.

By the way, you can always check the available options either by `qbt <command> --help` command or [online](https://github.com/fedarovich/qbittorrent-cli/wiki/command-reference).

Regarding the second question, alas, qBittorent API does not allow to enable superseed when add a torrent.

**Comment by foxi69** [comment]
sorry, thanks!
