### ISSUE TITLE
Add ability to manually enable or disable alternative limits

### ISSUE THREAD

**Issue by Saxtus** [fedarovich/qbittorrent-cli#45]
The `server settings speed` has no command to manually enable or disable alternative limits regardless of the current schedule.
If possible, add this feature.

**Comment by fedarovich** [comment]
I guess you are looking for [this command](https://github.com/fedarovich/qbittorrent-cli/wiki/qbt-global-limit-alternative):
```
qbt global limit alternative --set true
```
```
qbt global limit alternative --set false
```

**Comment by Saxtus** [comment]
You are absolutely right, I don't know how I missed that. Maybe I was expecting it in the speed category. I've tested it and works fine, so I am closing this issue and apologies for me creating it. Thank you for building this great program!
