### ISSUE TITLE
rename folders

### ISSUE THREAD

**Issue by dga4130-renato** [fedarovich/qbittorrent-cli#46]
there is an option to rename files , can an option be added  to rename folders instead of files

**Comment by fedarovich** [comment]
Unfortunately, qBittorrent does not support renaming folders at the moment.
If the developers of qBittorrent add this ability, I will add it to this tool too.

**Comment by fedarovich** [comment]
It looks like the required API has been added in one of the latest versions, so I can implement this feature.

**Comment by dga4130-renato** [comment]
Cool !! I am working on a cut rename foldername that cleans up the name as movie name and date . I could use the qbt to rename it
