### ISSUE TITLE
ubuntu hirsute

### ISSUE THREAD

**Issue by dga4130-renato** [fedarovich/qbittorrent-cli#47]
Would it be possible to upgrade the ppa for ubuntu hirsute ?
actually i am using the ppa but with groovy version. work perfect.

**Comment by fedarovich** [comment]
Hirsute is now officially supported.
As Linux package repositories has been moved, please follow the [installation guide](https://github.com/fedarovich/qbittorrent-cli/wiki/Setup-Linux) to update the repository.
