### ISSUE TITLE
Bintray will stop hosting packages in February 2022

### ISSUE THREAD

**Issue by MCOfficer** [fedarovich/qbittorrent-cli#48]
As per [this post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), bintray is approaching its EOL. You probably want to switch to a different hoster before that date. 

I have heard of fury.io, but there's probably more alternatives out there.

**Comment by dga4130-renato** [comment]
unable to update... seens bintray is dead

**Comment by fedarovich** [comment]
The move to other hosting is in progress.

**Comment by fedarovich** [comment]
**Linux package repositories has been moved! If you are using qBittorrent CLI 1.6 or earlier, please follow the [installation guide](https://github.com/fedarovich/qbittorrent-cli/wiki/Setup-Linux) to update the repository.**
