### ISSUE TITLE
Feature request: option "-f" for "qbt torrent resume" command

### ISSUE THREAD

**Issue by jducaud** [fedarovich/qbittorrent-cli#50]
Hello,

Great work for this amazingly efficient qBittorrent CLI!

It seems it misses the "_force resume_" feature of qBittorrent WebUI.

Would it be possible to add (as it is implemented for the `qbt torrent delete` command) a `-f` option to the `qbt torrent resume` command?

Regards,
Jerome.

**Comment by Jarsky** [comment]
Hi there, 

I really like this tool. Its useful for me to automatically pause the torrents to release file locks and allow them to be moved off my cache to storage.
But I have issues with torrents seeding properly so I normally set them to forced resume. 
Would be great if we could get this feature added as @jducaud requested.

**Comment by Jarsky** [comment]
this is done @jducaud 
you can use the below command once the author has published a release (or you can clone the git and build it)

`qbt torrent force-resume HASH|ALL`

**Comment by jducaud** [comment]
Thank you @Jarsky !

**Comment by fedarovich** [comment]
I've published the release with this pull request
