### ISSUE TITLE
unable to update 

### ISSUE THREAD

**Issue by dga4130-renato** [fedarovich/qbittorrent-cli#52]
Ignored:3 https://dl.bintray.com/fedarovich/qbittorrent-cli-debian groovy InRelease
https://dl.bintray.com/fedarovich/qbittorrent-cli-debian/ does not contain groovy neither hirsute

**Comment by fedarovich** [comment]
Bintray will stop working in a week, so the repositories are being moved to another hosting. Once the move is complete, I'll provide the instructions for the new hosting.
The packages for groovy and hirsute will also be there.

**Comment by dga4130-renato** [comment]
Great ! thanks

**Comment by fedarovich** [comment]
Linux package repositories has been moved! If you are using qBittorrent CLI 1.6 or earlier, please follow the [installation guide](https://github.com/fedarovich/qbittorrent-cli/wiki/Setup-Linux) to update the repository.

**Comment by dga4130-renato** [comment]
Done ! really thanks for all
it's a great prg , and it's vital for my system automation
