### ISSUE TITLE
Powershell - The handle is invalid

### ISSUE THREAD

**Issue by LordZozzy** [fedarovich/qbittorrent-cli#53]
When issuing the torrent list command with any of the arguments (except for the help argument), it throws a "The handle is invalid" error.
The error is not present when running the same command from CMD.exe.
Torrent add works fine.

![image](https://user-images.githubusercontent.com/29288053/118786005-b4526700-b891-11eb-9065-3b00d79f7734.png)

OS: WinSrv2016
PS version: 5.1
qbt-cli version: 1.7.21116.1
QBT version: 4.3.5

**Comment by LordZozzy** [comment]
?

**Comment by Rand-Random** [comment]
You can overcome the issue by specifing a --format as json or csv.
https://github.com/fedarovich/qbittorrent-cli/wiki/Output-Formats

the default output format, tries to make the output as beautiful as possible for the window, but when you run the command without a window it will fail with this exception.
