### ISSUE TITLE
How does share --time-limit work?

### ISSUE THREAD

**Issue by KnifeFed** [fedarovich/qbittorrent-cli#58]
I'm trying to figure out how `--time-limit` actually works. It says the format is `[d.]HH:mm[:ss]` but if I run:

`qbt torrent share <HASH> --time-limit 1.00:00:00` 
It sets 86400 minutes = 60 days. `--time-limit 1` sets the same.

`--time-limit 0.10:00:00` sets 36000 minutes = 25 days.

`--time-limit 01:00` sets 3600 minutes = 2.5 days.

I really don't understand how it's supposed to work.

**Comment by fedarovich** [comment]
Fixed in [1.7.22220.1](https://github.com/fedarovich/qbittorrent-cli/releases/tag/v1.7.22220.1)
