### ISSUE TITLE
Segfault on setting password or using app when password is set

### ISSUE THREAD

**Issue by alpha-tango-kilo** [fedarovich/qbittorrent-cli#63]
`qbt settings set password -y` segfaults after you press enter to submit the password

If you manually set the password in `settings.json` the program segfaults if it does anything that requires authentication

`qbt --version` reports v1.0.0

However given I'm using `qbt` within [linuxserver/docker-qbittorrent](https://github.com/linuxserver/docker-qbittorrent) I think the version I'm using is a lot more recent, v1.7 by the looks of it? The docker image pulls in [this](https://github.com/linuxserver/docker-qbittorrent/releases/tag/qbt-1.7)

I'm aware of the security implications but would still like to be able to do this even if the password is stored in plaintext. Alternatively, environment variables for login credentials would be a handy alternative

**Comment by fedarovich** [comment]
I've pushed a fix for the issue and will update the release this weekend.

As I started to provide an Alpine release only last week, I guess [linuxserver/docker-qbittorrent](https://github.com/linuxserver/docker-qbittorrent) build it themselves from the latest source but do not set the version while building, so it defaults to v1.0.0.

**Comment by alpha-tango-kilo** [comment]
Awesome thank you for fixing that so quickly!
