### ISSUE TITLE
A newer version of qBittorrent is required for this command

### ISSUE THREAD

**Issue by reshetnyakag** [fedarovich/qbittorrent-cli#66]
When I try to rename a file (qbt torrent file rename $hash -f $id --name "newName"), I get the error:
_A newer version of qBittorrent is required for this command.
API 2.4.0 must be supported._
qBittorrent version: 4.4.3.1
qbittorrent-cli version: 1.7.22127.1

**Comment by fedarovich** [comment]
Fixed in [1.7.22220.1](https://github.com/fedarovich/qbittorrent-cli/releases/tag/v1.7.22220.1)
