### ISSUE TITLE
Windows install via chocolatey

### ISSUE THREAD

**Issue by TgSeed** [fedarovich/qbittorrent-cli#67]
Hello,
Well i know it is possible but It has an small bug.

choco tries to get msi from `/releases/download/1.7.221127.1/` which is wrong because the version tags has a `v` at starts so it should be `/releases/download/vNNN/`.
Because of that GetResponse errors out with a 404 Not found status

**Comment by fedarovich** [comment]
Fixed in [1.7.22220.1](https://github.com/fedarovich/qbittorrent-cli/releases/tag/v1.7.22220.1)
