### ISSUE TITLE
Fedora 36 uses libssl 3.0 which apparently isn't supported by qbt

### ISSUE THREAD

**Issue by reticle5** [fedarovich/qbittorrent-cli#73]
Hi all, just built a replacement for my old Ubuntu server with Fedora 36. The libssl that comes with this is libssl3.0.5. When I run qbt, I get the message "No usable version of libssl was found". Qbt then promptly core dumps.

Anybody else come across this ?

Had to use the fedora 34 repo as that's the latest one I could find.

**Comment by fedarovich** [comment]
Hi,

I'll try to find some time this weekend and release a new version for fedora 36. Meanwhile, you can use these binaries which I expect to work with libssl 3.0: https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.7.22220.1/qbt-linux-x64-net6-1.7.22220.1.tar.gz

**Comment by reticle5** [comment]
Thanks. That tar file worked perfectly. Just so you know, Fedora 37 dropped about a week ago.

**Comment by fedarovich** [comment]
I've published a new version supporting Fedora 36 and 37
