### ISSUE TITLE
Set file priority in batch

### ISSUE THREAD

**Issue by duanluan** [fedarovich/qbittorrent-cli#74]
There is a Torrent file with at least 10,000 files, and I only need to download one of them. If I go to set the priority one by one, it is very slow and easy to get stuck.
Is it possible to set the priority of multiple files or all files at once?

**Comment by fedarovich** [comment]
Not directly, but can achieve it with some command line scripting.

On powershell you can just use the built-in syntax, while on bash you can use `xargs` command.

Some examples of using them can be found here: https://github.com/fedarovich/qbittorrent-cli/discussions/64

**Comment by duanluan** [comment]
> Some examples of using them can be found here: #64

```bash
(qbt torrent file list d929fc6b92bd4e6e14257c2c97e1e2893d449df8 -F csv | ConvertFrom-csv).Id | %{& qbt torrent file priority d929fc6b92bd4e6e14257c2c97e1e2893d449df8 -f $_ -s SKIP}
```

This method is not stuck, but it is still particularly slow, after ten minutes only a small part of the update, unlike the client side where you can cancel the download of all files with one click.
Is there some way to call the client side functions directly instead of just calling the Web UI?

[demo-torrent.zip](https://github.com/fedarovich/qbittorrent-cli/files/9989735/demo-torrent.zip)

**Comment by duanluan** [comment]
@fedarovich How should I use it?

**Comment by fedarovich** [comment]
Sorry, it looks like I associated this issue with a wrong commit.

But anyway, I'll add this feature in the upcoming version 1.8, so it will be possible to specify multiple `--file` options in a single command which will work significantly faster.

I'm planning to make the release by the end of this year, i.e. in the upcoming two weeks.
