### ISSUE TITLE
Ubuntu install issue

### ISSUE THREAD

**Issue by leni8ec** [fedarovich/qbittorrent-cli#77]
I'm not good with Ubuntu, I did everything according to [instructions](https://github.com/fedarovich/qbittorrent-cli/wiki/Setup-Linux#ubuntu-2204-jammy-mint-21x), but there is no result.

What could be the problem?

![image](https://user-images.githubusercontent.com/2379473/212026043-91a098d2-5bfb-4d5a-a64c-2fcf16451dea.png)
---

Ubuntu Server 22.04.01 LTS (jammy) 
Connect via ssh

**Comment by fedarovich** [comment]
It looks like you've missed [step 3](https://github.com/fedarovich/qbittorrent-cli/wiki/Setup-Linux#step-3-install-qbittorrent-cli) from the instructions.
```
sudo apt update
sudo apt install qbittorrent-cli
```

**Comment by leni8ec** [comment]
Oh, sorry!

Thanks! 

But it should be noted. that this item is not visible visually in the list of listed operating systems
