### ISSUE TITLE
Modified time stamp changed after loading from qbittorent

### ISSUE THREAD

**Issue by kenshinnmt** [fedarovich/qbittorrent-cli#79]
"Modified time stamp" of folder, sub folder and files changed after loading from qbittorent
How can I keep the modified date attribute the same as the torrent's creation directory

Picture for issues below
https://imgur.com/NgbZxpp
Sorry, I used Google Translate

**Comment by fedarovich** [comment]
I don't think it relates to this utility, as it's just a command line interface for qBittorrent.
