### ISSUE TITLE
Ability to redirect stdout [Feature Request]

### ISSUE THREAD

**Issue by TheArkive** [fedarovich/qbittorrent-cli#85]
I believe that #36 is having a similar issue that I'm having.  Apparently qbt won't allow stdout to be redirected away from the console that calls it in Windows.
Any time I try to redirect stdout I get an error message "The handle is invalid."  Of course standard redirection works:

```
qbt torrent list > file.txt
```

But this requires disk usage, and I'm going to avoid that as much as possible.

But any other means of special handling/redirecting of stdout doesn't seem to be allowed at the moment.  Fortunately for my uses I don't absolutely needs this, though it would be very nice.

Any chance of getting this feature in the future?

**Comment by fedarovich** [comment]
I cannot reproduce this issue, however I can recommend to use JSON or CSV output format for your use case. For example,
```
qbt torrent list -F json > file.txt
```
