### ISSUE TITLE
Detected virus during scan job

### ISSUE THREAD

**Issue by Tr4ncer** [fedarovich/qbittorrent-cli#86]
Virus scan found a problem with the file below.

AntivirusEngine = ClamAV
qbittorrent-cli/hostpolicy.dll: Win.Packed.Generickdz-10003157-0 FOUND

https://www.clamav.net/

**Comment by fedarovich** [comment]
It's a false positive from ClamAV:

https://www.virustotal.com/gui/file/4ad88d88f5d04f6c8a28f681b297313414a2c852817327133cad97ad47b0b455

Please note that hostpolicy.dll is a file provided (and signed) by Microsoft and is a part of .Net Core 3.1 distribution.

**Comment by Tr4ncer** [comment]
ok thanks 👍

**Comment by Tr4ncer** [comment]
I reported the false positive to the ClamAV team

![image](https://github.com/fedarovich/qbittorrent-cli/assets/39873273/7f547675-8102-48f9-bf26-4b5ac0f06432)
