### ISSUE TITLE
Support for Debian 12

### ISSUE THREAD

**Issue by MVasuki1** [fedarovich/qbittorrent-cli#90]

**Comment by sir-wilhelm** [comment]
@fedarovich any plans to bundle/release a Debian 12 version? 

-- I'd be happy to help if there is anything I can do.

**Comment by fedarovich** [comment]
Yes, I'm preparing release 1.8.x that will include support for the latest OS versions (incl. Debian 12), as well as some new features and bug fixes.

I'm planning to release it by the end of the year, not sure yet about exact timeline.
