### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by jshirle2** [fedarovich/qbittorrent-cli#92]
I have a VM using qbittorrent on FreeBSD. Is there any path for me to install this there? I would love the ability to have access to this. 

Thanks!

**Comment by fedarovich** [comment]
Hi,
I guess you can try to download [qbt-netfx46-1.7.22315.1.tar.gz](https://github.com/fedarovich/qbittorrent-cli/releases/download/v1.7.22315.1/qbt-netfx46-1.7.22315.1.tar.gz) and try to run it using Mono, as described here: https://github.com/fedarovich/qbittorrent-cli/wiki/Setup-Advanced-PlatformAgnostic
